### ISSUE TITLE
Node-sass package missing from fresh install

### ISSUE THREAD

**Issue by avenla-mlindman** [danijelh/aspnetcore-vue-typescript-template#1] opened 2018-11-16 06:09 UTC
I had to install node-sass manually

npm install -save-dev node-sass

Before the js side of the app would build properly.

I quess people who use sass usually have this installed globally, so it's missing from the template?

**Comment by danijelh** [comment] 2018-11-16 07:10
**Node sass** version 4.9.4 is listed in `package.json` as a dependency so I believe this is not the issue. I have not been able to reproduce this as it is installing and working as expected. Maybe dev dependencies were not installed on your part.

Nevertheless, I am shipping a minor feature next week and will also look into this with more detail. 

I am closing the issue for now because the package is present as a dependency and is working as expected.

**Closed by danijelh** 2018-11-16 07:10 UTC
